/** Colonne export legacy titoli di giugno (senza Fatt, NumEc, CdTiPo). */
export const PREMI_PROVVIGIONI_COLUMNS = [
  { key: "nomeCliente", header: "Nome Cliente" },
  { key: "nomeAE", header: "Nome A/E" },
  { key: "nomeSpecialist", header: "Nome Specialist" },
  { key: "cdComp", header: "CdComp" },
  { key: "nomeCompagnia", header: "Nome Compagnia" },
  { key: "percRiparto", header: "%Riparto" },
  { key: "ramo", header: "Ramo" },
  { key: "gruppoFinCompagnia", header: "Gruppo Fin Compagnia" },
  { key: "gruppoStatCompagnia", header: "Gruppo Stat Compagnia" },
  { key: "polizza", header: "Polizza" },
  { key: "appendice", header: "Appendice" },
  { key: "descrizione", header: "Descrizione" },
  { key: "compContabile", header: "Comp_Contabile" },
  { key: "compAssicurativa", header: "Comp_Assicurativa" },
  { key: "inizPol", header: "Iniz Pol" },
  { key: "scadPol", header: "Scad Pol" },
  { key: "inizGar", header: "Iniz Gar" },
  { key: "scadGar", header: "Scad Gar" },
  { key: "premio", header: "Premio" },
  { key: "imponibile", header: "Imponibile" },
  { key: "tasse", header: "Tasse" },
  { key: "attive", header: "Attive" },
  { key: "passive", header: "Passive" },
  { key: "nomeProduttore", header: "Nome Produttore" },
  { key: "dtCopertura", header: "Dt Copertura" },
  { key: "dtIncasso", header: "Dt Incasso" },
  { key: "contoInc", header: "ContoInc" },
  { key: "fil", header: "Fil" },
  { key: "tipoPortafoglio", header: "Tipo Portafoglio" },
  { key: "zona", header: "Zona" },
  { key: "indotto", header: "Indotto" },
  { key: "settore", header: "Settore" },
  { key: "contratto", header: "Contratto" },
  { key: "fatturato", header: "Fatturato" },
  { key: "dipendenti", header: "Dipendenti" },
  { key: "incassato", header: "Incassato" },
  { key: "percProvv", header: "% Provv." },
  { key: "pagata", header: "Provv. Incassata" },
] as const;

export type PremiProvvigioniRow = Record<(typeof PREMI_PROVVIGIONI_COLUMNS)[number]["key"], string | number | null>;
