DROP VIEW IF EXISTS v_portafoglio_titoli;

CREATE VIEW v_portafoglio_titoli AS
SELECT t.id,
    t.numero_titolo,
    t.cliente_id,
    t.prodotto_id,
    t.ufficio_id,
    t.produttore_id,
    t.premio_lordo,
    t.importo_incassato,
    t.data_incasso,
    t.stato,
    t.note,
    t.created_at,
    t.updated_at,
    t.search_vector,
    t.cliente_anagrafica_id,
    t.data_scadenza,
    t.compagnia_id,
    t.ramo_id,
    t.gruppo_ramo,
    t.specialist,
    t.tipo_portafoglio,
    t.cig_rif,
    t.vincolo,
    t.descrizione_polizza,
    t.appendice,
    t.riga,
    t.targa_telaio,
    t.durata_da,
    t.durata_a,
    t.anni_durata,
    t.garanzia_da,
    t.garanzia_a,
    t.data_competenza,
    t.limite_mora,
    t.mora_giorni,
    t.rate,
    t.tipo_rinnovo,
    t.disdetta_mesi,
    t.regolazione,
    t.tipo_lettera_regolazione,
    t.tipo_scadenza,
    t.giorni_presentazione,
    t.periodicita,
    t.libro_matricola,
    t.rimborso,
    t.valuta,
    t.cambio,
    t.indicizzata,
    t.no_calcolo_tasse,
    t.premio_netto,
    t.addizionali,
    t.tasse,
    t.provvigioni_firma,
    t.provvigioni_quietanza,
    t.premio_netto_quietanza,
    t.addizionali_quietanza,
    t.tasse_quietanza,
    t.pag_diretto_compagnia,
    t.emissione_fee,
    t.formato_elettronico,
    t.sostituisce_polizza,
    t.sostituisce_riga,
    t.sostituisce_appendice,
    t.storno_polizza,
    t.storno_riga,
    t.storno_appendice,
    t.commerciale_id,
    t.percentuale_commerciale,
    t.percentuale_riparto,
    t.tipo_mandatario,
    t.risk_type,
    t.prodotto_nome,
    t.comp_contabile,
    t.comp_assicurativa,
    t.tipo_incasso,
    t.conto_incasso,
    t.id_legacy,
    t.produttore_nome,
    t.ae_nome,
    t.filiale,
    t.data_sospensione,
    t.limite_riattivazione,
    t.data_riattivazione,
    t.motivo_sospensione,
    t.data_messa_cassa,
    t.data_pagamento,
    t.data_decorrenza_rinnovo,
    t.conferimento_gestito,
    t.fondi_ricevuti,
    t.data_conferimento_gestito,
    c.nome AS compagnia_nome,
    c.codice AS compagnia_codice,
    r.descrizione AS ramo_nome,
    r.codice AS ramo_codice,
    COALESCE(cl.ragione_sociale, TRIM(BOTH FROM (COALESCE(cl.cognome, ''::text) || ' '::text) || COALESCE(cl.nome, ''::text))) AS cliente_nome_display,
    cl.codice_ricerca AS cliente_codice,
    cl.cognome AS cliente_cognome,
    cl.nome AS cliente_nome,
    cl.ragione_sociale AS cliente_ragione_sociale,
    cl.codice_fiscale AS cliente_codice_fiscale,
    cl.tipo_cliente AS cliente_tipo,
    u.nome_ufficio
   FROM titoli t
     LEFT JOIN compagnie c ON c.id = t.compagnia_id
     LEFT JOIN rami r ON r.id = t.ramo_id
     LEFT JOIN prodotti p ON p.id = t.prodotto_id
     LEFT JOIN clienti cl ON cl.id = t.cliente_anagrafica_id
     LEFT JOIN uffici u ON u.id = t.ufficio_id;