
-- 1. Delete old tipi_mandatario records
DELETE FROM tipi_mandatario;

-- 2. Insert 14 new tipi_mandatario from Excel
INSERT INTO tipi_mandatario (codice, descrizione, attivo) VALUES
  ('01', 'Direzione', true),
  ('02', 'Gerenza', true),
  ('03', 'Agenzia Generale', true),
  ('04', 'Agente Monomandatario', true),
  ('11', 'Agente Multimandatario', true),
  ('12', 'Broker', true),
  ('13', 'Sub-Agente', true),
  ('21', 'Compagnia Estera', true),
  ('22', 'Agente Estero', true),
  ('23', 'Broker Estero', true),
  ('31', 'Lloyd''s Coverholder', true),
  ('32', 'Lloyd''s Broker', true),
  ('33', 'Lloyd''s Service Company', true),
  ('99', 'Altro', true);

-- 3. Update titoli that had 'Broker' to new code '12'
UPDATE titoli SET tipo_mandatario = '12' WHERE tipo_mandatario = 'Broker';

-- 4. Delete old lookup_tipo_documento records
DELETE FROM lookup_tipo_documento;

-- 5. Insert 91 tipo documento records from Excel
INSERT INTO lookup_tipo_documento (codice, descrizione, attivo, visibile, clienti, compagnie, polizze, trattative, contrattuali, prod, firma) VALUES
  ('1', 'DOCUMENTI CONTRATTUALI', true, false, false, false, true, false, true, false, NULL),
  ('11', 'Polizza Firmata', true, false, false, false, true, false, true, false, NULL),
  ('11-1', 'Polizza Non Firmata', true, false, false, false, true, false, true, false, NULL),
  ('11-2', 'Regolazione Premio', true, false, false, false, true, false, true, false, NULL),
  ('12', 'Appendice Firmata', true, false, false, false, true, false, true, false, NULL),
  ('12-1', 'Appendice Non Firmata', true, false, false, false, true, false, true, false, NULL),
  ('12-4', 'Questionario adeguatezza', true, false, false, false, false, true, false, false, NULL),
  ('12-5', 'Modulo adeguata verifica - AML', true, false, false, false, false, true, false, false, NULL),
  ('13', 'Polizza Frontespizio', true, false, false, false, true, false, false, false, NULL),
  ('14', 'Appendice Frontespizio', true, false, false, false, true, false, false, false, NULL),
  ('15', 'Coperture Provvisorie', true, false, false, false, true, false, false, false, NULL),
  ('16', 'Gestione Applicazione', true, false, false, false, true, false, false, false, NULL),
  ('16-1', 'Contrassegno', true, false, false, false, true, false, false, false, NULL),
  ('17', 'RCA Libretto e Attestato', true, false, false, false, true, false, true, false, NULL),
  ('17-1', 'ARD Libretto', true, false, false, false, true, false, true, false, NULL),
  ('18', 'Condizioni di polizza', true, false, false, false, true, false, true, false, NULL),
  ('18-1', 'Lettera di svincolo', true, false, false, false, true, false, false, false, NULL),
  ('19', 'Cover Note Lloyds', true, false, false, false, true, false, false, false, NULL),
  ('1AL3', 'Allegato 3', true, false, false, false, true, false, true, false, NULL),
  ('1AL4', 'Allegato 4', true, false, false, false, true, false, true, false, NULL),
  ('1ALC', 'Conferma Invio documentazione mail', true, true, true, false, true, false, true, false, NULL),
  ('1ALF', 'Certificato Firma', true, false, false, false, false, true, false, false, NULL),
  ('1ALM', 'Allegato MUP', true, false, false, false, true, false, true, false, NULL),
  ('1ALP', 'Informativa Privacy', true, true, true, false, true, false, true, false, 'S'),
  ('1ALR', 'Ricevuta Consegna documenti', true, true, true, false, true, false, true, false, 'S'),
  ('1ALT', 'Allegato 4Ter', true, false, false, false, false, true, false, false, NULL),
  ('1ALZ', 'Raccomandazione Personalizzata', true, false, false, false, false, true, false, false, NULL),
  ('1ARP', 'Richiesta Pagamento Premio', true, true, true, false, true, false, true, false, NULL),
  ('1DOF', 'Documenti Firmati Elettronicamente', true, false, false, false, false, true, false, false, NULL),
  ('2', 'CORRISPONDENZA', true, false, true, true, true, true, false, true, NULL),
  ('20', 'Fascicolo informativo compagnia', true, false, false, true, false, false, false, true, NULL),
  ('2001', 'Privacy compagnia', true, false, false, true, false, false, false, true, NULL),
  ('21', 'Trattativa iniziale', true, false, false, false, false, true, false, false, NULL),
  ('2101', 'Presentazione e quotazioni', true, false, false, false, false, true, false, false, NULL),
  ('2102', 'Presentazione al Cliente', true, true, false, false, false, false, false, false, NULL),
  ('2103', 'Ordine Fermo', true, false, false, false, true, true, false, false, NULL),
  ('2105', 'Preventivi RCA', true, false, false, false, true, false, false, false, NULL),
  ('2106', 'Conferma copertura compagnia', true, false, false, true, false, false, false, true, NULL),
  ('2108', 'Conferma copertura a cliente', true, true, false, false, false, false, false, false, NULL),
  ('22', 'CORRISPONDENZA VARIA', true, false, true, true, true, true, false, true, NULL),
  ('2201', 'Comunicazioni al Cliente', true, true, false, false, false, false, false, false, NULL),
  ('2202', 'Comunicazioni alle Compagnie', true, false, false, true, false, false, false, true, NULL),
  ('2203', 'Corrispondenza mail', true, true, true, true, true, true, false, true, NULL),
  ('2204', 'Corrispondenza mail 1', true, true, true, true, true, true, false, true, NULL),
  ('2205', 'Scheda di Polizza', true, true, true, true, true, true, false, true, NULL),
  ('2206', 'Questionario Compilato', true, true, true, true, true, true, false, true, NULL),
  ('2207', 'Quotazione Compagnia', true, true, true, true, true, true, false, true, NULL),
  ('2208', 'Comunicazioni dalle compagnie', true, false, false, true, true, true, false, true, NULL),
  ('2209', 'Comunicazioni dal cliente', true, true, false, false, false, true, false, false, NULL),
  ('22AV', 'Avviso di scadenza', true, true, false, false, false, false, false, false, NULL),
  ('22EC', 'Estratto Conto al Cliente', true, true, false, false, false, false, false, false, NULL),
  ('23', 'ADEMPIMENTI PERIODICI', true, false, false, false, false, false, false, false, NULL),
  ('2301', 'Richiesta dati regolazione', true, true, false, false, false, false, false, false, NULL),
  ('2302', 'Trasmissione dati regolazione', true, false, false, true, false, false, false, true, NULL),
  ('2303', 'Altri Adempimenti', true, true, true, false, false, false, false, true, NULL),
  ('24', 'DISDETTA', true, false, false, false, false, false, false, false, NULL),
  ('2401', 'Lettera di disdetta', true, true, true, true, false, false, false, true, NULL),
  ('2402', 'Trasmissione lettera disdetta', true, true, true, true, false, false, false, true, NULL),
  ('3', 'AMMINISTRAZIONE / CONTABILITA''', true, false, false, false, false, false, false, false, NULL),
  ('31', 'Quietanze', true, true, true, true, false, false, false, true, NULL),
  ('32', 'Trasmissione quietanze', true, true, true, false, false, false, false, true, NULL),
  ('33', 'Solleciti', true, true, true, false, false, false, false, true, NULL),
  ('34', 'Varie', true, true, true, false, false, false, false, true, NULL),
  ('35', 'Restituzione quietanze', true, true, true, false, false, false, false, true, NULL),
  ('36', 'Avviso di incasso', true, true, true, true, false, false, false, false, NULL),
  ('4', 'GENERAL FILE', true, false, false, false, false, false, false, false, NULL),
  ('40', 'Consenso Privacy', true, true, false, true, false, false, false, false, NULL),
  ('41', 'Bilanci', true, true, false, false, false, true, false, false, NULL),
  ('42', 'Survey Report', true, true, false, false, false, true, false, false, NULL),
  ('43', 'Questionari', true, true, false, false, false, true, false, false, NULL),
  ('44', 'Stime o elenchi', true, true, false, false, false, true, false, false, NULL),
  ('45', 'Altri Documenti', true, true, true, true, true, true, false, true, NULL),
  ('46', 'Bando di gara', true, true, true, false, false, true, false, true, NULL),
  ('47', 'Lettera aggiudicazione', true, true, true, false, false, true, false, true, NULL),
  ('48', 'Certificato collaudo', true, true, true, false, false, true, false, true, NULL),
  ('49', 'Contratto d''appalto tra le parti', true, true, true, false, false, true, false, true, NULL),
  ('5', 'COMPAGNIE', true, false, false, true, false, false, false, true, NULL),
  ('51', 'Mandati', true, false, false, true, false, false, false, true, NULL),
  ('52', 'Bonifico Compagnia', true, false, false, true, false, false, false, false, NULL),
  ('53', 'Bordereau Sinistri', true, false, false, true, false, false, false, false, NULL),
  ('54', 'Trasmissione documenti firmati', true, false, false, true, false, false, false, false, NULL),
  ('6', 'CLIENTI', true, false, true, false, false, false, false, false, NULL),
  ('61', 'Mandato di brokeraggio', true, true, false, false, false, false, false, false, 'S'),
  ('61E', 'Mandato esplorativo', true, true, false, true, false, false, false, false, NULL),
  ('61O', 'Mandato esplorativo ad obiettivo', true, true, false, true, false, false, false, false, NULL),
  ('62', 'Ricevuta Adeguatezza 7/A 7/B', true, true, false, false, false, false, false, false, NULL),
  ('63', 'Consenso invio documenti x email', true, true, false, false, false, false, false, false, NULL),
  ('64', 'Ricevuta doc. IVASS', true, true, false, true, false, false, false, false, NULL),
  ('65', 'Consenso tratt. dati pers.', true, true, false, true, false, false, false, false, NULL),
  ('66', 'Doc. coerenza', true, true, false, true, false, false, false, false, NULL),
  ('67', 'Accordo di collaborazione', true, false, false, false, false, false, false, true, NULL);
