-- Step 1: Remove FK references from titoli
UPDATE titoli SET ramo_id = NULL WHERE ramo_id IS NOT NULL;

-- Step 2: Delete fake data
DELETE FROM rami;
DELETE FROM gruppi_ramo;

-- Step 3: Insert real gruppi_ramo
INSERT INTO gruppi_ramo (codice, descrizione, attivo) VALUES
('ZL', 'INCENDIO FURTO RISCHI TECNOLOGICI', true),
('ZT', 'TRASPORTI', true),
('ZD', 'CORPI', true),
('ZY', 'ALTRI RAMI DANNI', true),
('ZP', 'R.C.T.', true),
('ZN', 'INFORTUNI', true),
('ZC', 'CREDITO CAUZIONI', true),
('DI', 'ASSISTENZA', true),
('ZM', 'MALATTIA', true),
('ZQ', 'R.C.A.', true),
('ZS', 'TUTELA GIUDIZIARIA', true),
('ZV', 'VITA', true);

-- Step 4: Insert 182 rami reali
INSERT INTO rami (codice, descrizione, gruppo_ramo_id, aliquota_tasse_ramo, aliquota_tasse_ard, attivo) VALUES
('A1', 'ALL RISKS ESTERO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.5, 0, true),
('AI', 'LEASING IMMOBILIARE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('AR', 'ALL RISKS', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('ARA', 'ALL RISK CENTRALI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('ARB', 'ALL RISK IMPIANTI FOTOVOLTAICI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('ARC', 'ALL RISK OPERE D''ARTE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('ARD', 'ALL PATRIMONIO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('ARG', 'ALL RISK PATRIMONIO VINCOLATO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('ARH', 'ALL RISK SCUOLE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('ARI', 'ALL RISK STRUMENTI MUSICALI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('AS', 'LEASING STRUMENTALE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('AT', 'MOSTRE D''ARTE', (SELECT id FROM gruppi_ramo WHERE codice='ZT'), 22.25, 12.5, true),
('BB', 'BBB-BANKERS BLANKET BOND', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 0, 0, true),
('BC', 'AVIAZIONE CORPI', (SELECT id FROM gruppi_ramo WHERE codice='ZD'), 5, 0, true),
('BG', 'AVIAZIONE GUERRA', (SELECT id FROM gruppi_ramo WHERE codice='ZY'), 5, 0, true),
('BG2', 'P&I', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('BGA', 'AVIATION', (SELECT id FROM gruppi_ramo WHERE codice='ZY'), 5, 5, true),
('BI', 'AVIAZIONE INFORTUNI', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 0, true),
('BR', 'AVIAZIONE R. C.', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 0, true),
('CA', 'CAUZIONI ANTICIPAZIONI', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CAF', 'EVENTI SPECIALI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 0, 0, true),
('CAT', 'CATASTROFALI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('CB', 'CREDITO ILOR', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CC', 'CREDITO COMMERCIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CD', 'CAUZIONI DEFINITIVE', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CE', 'CREDITO IRPEF', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CF', 'CREDITO FIDEJUSSIONI IVA', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CG', 'CREDITO IRPEG', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CI', 'AUTENTICHE POL. IVA', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 2.5, 0, true),
('CN', 'AUTENTICA DI FIRMA', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 0.25, 0, true),
('CP', 'CAUZIONI PROVVISORIE', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CR', 'CAUZIONI SVINC. RIT. GAR.', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CS', 'CAUZIONI SVINCOLO DECIMI', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CT', 'CAUZIONI RATA DI SALDO', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('CW', 'DPO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 0, 0, true),
('CY', 'CYBER RISK', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('CZ', 'CAUZIONI SV. REV. PREZZI', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('DA', 'ASSISTENZA', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 10, 10, true),
('DAA', 'ASSISTENZA AL CITTADINO', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 10, 10, true),
('DAB', 'ASSISTENZA RCA', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 10, 10, true),
('DAC', 'ASSISTENZA-RC-INFORTUNI', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 10, 10, true),
('DAD', 'ASSISTENZA, R.C. INFORTUNI', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 0, 0, true),
('DAE', 'COVID-19', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 0, 0, true),
('DAF', 'TRIPY EQUALIZZATORE', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 0, 0, true),
('DAG', 'TRIPY VACANZA INSIEME', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 0, 0, true),
('DD', 'CORPI IMBARCAZIONI DIPOR.', (SELECT id FROM gruppi_ramo WHERE codice='ZD'), 12.5, 12.5, true),
('DE', 'CORPI DRONE', (SELECT id FROM gruppi_ramo WHERE codice='ZD'), 7.5, 7.5, true),
('DF', 'CORPI VEICOLI FERROVIARI', (SELECT id FROM gruppi_ramo WHERE codice='ZD'), 7.5, 7.5, true),
('DI', 'RC INQUINAMENTO', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('DIA', 'DIARIA DA RICOVERO', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 2.5, true),
('DN', 'CORPI NAVI', (SELECT id FROM gruppi_ramo WHERE codice='ZD'), 7.5, 7.5, true),
('DNA', 'CORPI NAUTICA', (SELECT id FROM gruppi_ramo WHERE codice='ZD'), 7.5, 7.5, true),
('DRA', 'A.R.D', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('DV', 'POLIZZA VIAGGI', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 0, 0, true),
('DVA', 'ASSISTENZA VIAGGI', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 0, 0, true),
('DW', 'CORPI WAR RISKS', (SELECT id FROM gruppi_ramo WHERE codice='ZD'), 7.5, 7.5, true),
('EC', 'CRISTALLI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 22.25, 22.25, true),
('FE', 'E.A.R.', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('FG', 'C.A.R./E.A.R.', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 21.25, 21.25, true),
('FID', 'FIDEJUSSIONE', (SELECT id FROM gruppi_ramo WHERE codice='ZC'), 12.5, 12.5, true),
('FR', 'FRANCHIGIE POL. KASKO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 0, 0, true),
('GC', 'C.A.R.', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 21.25, 21.25, true),
('GLA', 'GL. ATTIVITA''', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('GM', 'GUASTI MACCHINE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('HE', 'ELETTRONICA', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 21.25, 21.25, true),
('IB', 'FURTO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('IBA', 'FURTO/RAPINA CITTADINI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('IC', 'FURTO COMMERCIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('IG', 'FURTO GLOBALE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('II', 'FURTO INDUSTRIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('IP', 'FURTO PORTAVALORI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('IV', 'FURTO CIVILE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LA', 'INCENDIO AGRICOLO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LB', 'LEASING IMMOBILIARE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LC', 'INCENDIO CIVILE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LE', 'INCENDIO EXT. COVERAGE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LI', 'INCENDIO INDUSTRIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LM', 'INCENDIO COMMERCIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LN', 'EVENTI SPECIALI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LNA', 'RISCHIO PIOGGIA', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 0, 0, true),
('LO', 'INCENDIO RISCHI ORDINARI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LOA', 'INCENDIO E GAR. ACC. P.A.', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 0, 0, true),
('LP', 'INCENDIO PICCOLA INDUSTR.', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LQ', 'MULTIRISCHIO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LR', 'INCENDIO RISCHI INDUSTR.', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LS', 'INCENDIO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LSA', 'INCENDIO ELETTRONICA NON VINCOLATI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LSB', 'INCENDIO ELETTRONICA VINCOLATI', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LT', 'GLOBALE FABBRICATO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LTA', 'GLOBALE ABITAZIONE', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('LU', 'INCENDIO - FURTO', (SELECT id FROM gruppi_ramo WHERE codice='ZL'), 22.25, 22.25, true),
('MB', 'ANIMALI DOMESTICI', (SELECT id FROM gruppi_ramo WHERE codice='ZM'), 2.5, 2.5, true),
('MC', 'MALATTIA CUMULATIVA', (SELECT id FROM gruppi_ramo WHERE codice='ZM'), 2.5, 2.5, true),
('MCA', 'MALATTIA', (SELECT id FROM gruppi_ramo WHERE codice='ZM'), 2.5, 2.5, true),
('MI', 'MALATTIA INDIVIDUALE', (SELECT id FROM gruppi_ramo WHERE codice='ZM'), 2.5, 2.5, true),
('MS', 'SPESE MEDICHE', (SELECT id FROM gruppi_ramo WHERE codice='ZM'), 2.5, 2.5, true),
('NA', 'INFORTUNI CONDUCENTE', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 2.5, true),
('NB', 'INFORTUNI VOLONTARI', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 2.5, true),
('NC', 'INFORTUNI CUMULATIVA', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 2.5, true),
('NCA', 'INFORTUNI CUMULATIVA', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 0, 0, true),
('NI', 'INFORTUNI INDIVIDUALE', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 2.5, true),
('NIA', 'INFORTUNI', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 2.5, true),
('NS', 'INFORTUNI IND. SPORTIVI', (SELECT id FROM gruppi_ramo WHERE codice='ZN'), 2.5, 2.5, true),
('PA', 'R.C.T./O. escluso tasse', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 0, true),
('PB', 'RESP. CIVILE VERSO TERZI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PC', 'R.C.T./R.C.O', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PCA', 'RCTO + RC PATRIMONIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PCB', 'RC + TUTELA LEGALE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 0, 0, true),
('PD', 'R. C. DIVERSI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PDA', 'RC CENTRALE ENERGIA', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PDB', 'RC DRONE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PE', 'R. C. CAPOFAMIGLIA', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PF', 'R. C. FABBRICATI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PG', 'SPESE LEGALI', (SELECT id FROM gruppi_ramo WHERE codice='ZS'), 21.25, 21.25, true),
('PH', 'R.C.O.', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PI', 'R. C. AUTOVEICOLI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('PJ', 'FRANCHIGIE POL. RCA', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 0, 0, true),
('PL', 'DECENNALE POSTUMA', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PLA', 'RC POSTUMA QUINQUENNALE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PLB', 'RC PROF. POSTUMA', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 0, 0, true),
('PM', 'R. C. COMMERCIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PMA', 'R.C. AZIENDA AGRICOLA', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PN', 'R. C. INQUINAMENTO', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PO', 'R. C. VETTORE STRADALE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 13.5, 13.5, true),
('PP', 'R. C. PRODOTTI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PQ', 'ASSISTENZA SOCC. STRADALE', (SELECT id FROM gruppi_ramo WHERE codice='DI'), 22.25, 22.25, true),
('PR', 'R. C. PROFESSIONALE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRA', 'R.C. SANITARIA', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRB', 'R.C. VOLONTARI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRC', 'R.C. PROFESSIONALE COLPA GRAVE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRD', 'R.C. PROGETTISTI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRE', 'R.C. VERIFICATORI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRF', 'R.C. MEDIAZIONE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRG', 'CONVENZIONE FIMMG', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PRH', '3 VIRUS', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PS', 'R. C. PATRIMONIALE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PSA', 'RC PATRIMONIALE COLPA GRAVE', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PSB', 'R.C. PATR. DIPEN.', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 0, 0, true),
('PSC', 'R.C. PATR. TECNICI', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 0, 0, true),
('PT', 'D&O', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PU', 'COLPA GRAVE "RCP"', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PW', 'FRANCHIGIE POL. RCD', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 0, 0, true),
('PX', 'COLPA GRAVE "RCT"', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('PY', 'COLPA GRAVE "D&O"', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 22.25, true),
('QA', 'R. C. AUTO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QAB', 'LIBRO MATRICOLA', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 12.5, 13.5, true),
('QAC', 'RCA & ARD', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 12.5, 13.5, true),
('QB', 'RITIRO PATENTE', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 12.5, 13.5, true),
('QC', 'R. C. AUTOCARRI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QF', 'R. C. I/F AUTO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QG', 'R. C. I/F AUTOCARRI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QI', 'INCENDIO/FURTO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 13.5, 13.5, true),
('QK', 'KASKO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 13.5, 13.5, true),
('QKA', 'KASKO KM', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 13.5, 13.5, true),
('QKB', 'KASKO ENTE+AMM.RI/DIP.', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 13.5, 13.5, true),
('QKC', 'KASKO MEZZI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 13.5, 13.5, true),
('QM', 'R. C. MOTO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QN', 'R. C. NATANTI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QNA', 'RC+CORPI NAUTICA', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 0, 0, true),
('QO', 'R. C. I/F MOTO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QQ', 'R. C. MACCHINE AGRICOLE', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QR', 'R. C. I/F AUTOVEICOLI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QT', 'R. C. I/F NATANTI', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QU', 'R. C. I/F KASKO AUTO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 16, 13.5, true),
('QZ', 'INCENDIO/FURTO/KASKO', (SELECT id FROM gruppi_ramo WHERE codice='ZQ'), 13.5, 13.5, true),
('RA', 'TEMPORANEA CASO MORTE', (SELECT id FROM gruppi_ramo WHERE codice='ZV'), 0, 0, true),
('RB', 'T.F.R.', (SELECT id FROM gruppi_ramo WHERE codice='ZV'), 2.5, 2.5, true),
('RC', 'VITA COLLETTIVA', (SELECT id FROM gruppi_ramo WHERE codice='ZV'), 2.5, 2.5, true),
('RC1', 'TFM', (SELECT id FROM gruppi_ramo WHERE codice='ZV'), 0, 0, true),
('RD', 'TCM-IPT', (SELECT id FROM gruppi_ramo WHERE codice='ZV'), 0, 0, true),
('RI', 'VITA INDIVIDUALE', (SELECT id FROM gruppi_ramo WHERE codice='ZV'), 2.5, 2.5, true),
('RP', 'RISCHIO POLITICO', (SELECT id FROM gruppi_ramo WHERE codice='ZY'), 2.5, 0, true),
('RS', 'R.C. SPERIM. CLINICA', (SELECT id FROM gruppi_ramo WHERE codice='ZP'), 22.25, 0, true),
('SC', 'SPECIAL CONTINGENCY', (SELECT id FROM gruppi_ramo WHERE codice='ZY'), 22.5, 0, true),
('SL', 'TUTELA GIUDIZIARIA', (SELECT id FROM gruppi_ramo WHERE codice='ZS'), 21.25, 21.25, true),
('SL1', 'TUTELA GIUDIZIARIA GRAVE', (SELECT id FROM gruppi_ramo WHERE codice='ZS'), 21.25, 21.25, true),
('SL2', 'DONAZIONE', (SELECT id FROM gruppi_ramo WHERE codice='ZS'), 0, 0, true),
('SL3', 'TUTELA POSTUMA', (SELECT id FROM gruppi_ramo WHERE codice='ZS'), 0, 0, true),
('ST', 'STOCK IN TRANSIT', (SELECT id FROM gruppi_ramo WHERE codice='ZT'), 5, 0, true),
('TM', 'TRASPORTO MERCI', (SELECT id FROM gruppi_ramo WHERE codice='ZT'), 12.5, 12.5, true),
('TV', 'TRASPORTO VALORI', (SELECT id FROM gruppi_ramo WHERE codice='ZT'), 22.25, 22.25, true),
('ZY', 'ALTRI RAMI DANNI', (SELECT id FROM gruppi_ramo WHERE codice='ZY'), 0, 0, true);