-- Siti di settore e compagnie per Assistente Web (oltre a IVASS / ANIA / Normattiva).

INSERT INTO public.cb_bot_siti_autorizzati (nome, url, dominio, note) VALUES
  ('Preventivass', 'https://www.preventivass.it', 'preventivass.it', 'Settore — preventivatore RC auto IVASS'),
  ('Gazzetta Ufficiale', 'https://www.gazzettaufficiale.it', 'gazzettaufficiale.it', 'Settore — atti ufficiali'),
  ('EUR-Lex', 'https://eur-lex.europa.eu', 'eur-lex.europa.eu', 'Settore — normativa UE (IDD, Solvency)'),
  ('EIOPA', 'https://www.eiopa.europa.eu', 'eiopa.europa.eu', 'Settore — autorità europea assicurazioni'),
  ('Banca d''Italia', 'https://www.bancaditalia.it', 'bancaditalia.it', 'Settore — vigilanza e UIF'),
  ('Garante Privacy', 'https://www.garanteprivacy.it', 'garanteprivacy.it', 'Settore — GDPR e privacy'),
  ('COVIP', 'https://www.covip.it', 'covip.it', 'Settore — previdenza complementare'),
  ('CONSAP', 'https://www.consap.it', 'consap.it', 'Settore — Fondo vittime della strada'),
  ('Portale dell''automobilista', 'https://www.ilportaledellautomobilista.it', 'ilportaledellautomobilista.it', 'Settore — PRA / motorizzazione'),
  ('CONSOB', 'https://www.consob.it', 'consob.it', 'Settore — prodotti di investimento'),
  ('SACE', 'https://www.sace.it', 'sace.it', 'Settore — credito e cauzioni export'),
  ('AIBA', 'https://www.aiba.it', 'aiba.it', 'Settore — associazione broker'),
  ('SNA', 'https://www.sna.it', 'sna.it', 'Settore — sindacato agenti'),
  ('ANAPA', 'https://www.anapa.it', 'anapa.it', 'Settore — associazione agenti'),
  ('Insurance Europe', 'https://www.insuranceeurope.eu', 'insuranceeurope.eu', 'Settore — federazione europea'),
  ('Assinews', 'https://www.assinews.it', 'assinews.it', 'Settore — rassegna normativa e mercato'),
  ('Generali', 'https://www.generali.it', 'generali.it', 'Compagnia'),
  ('Unipol', 'https://www.unipol.it', 'unipol.it', 'Compagnia'),
  ('UnipolSai', 'https://www.unipolsai.it', 'unipolsai.it', 'Compagnia'),
  ('Allianz', 'https://www.allianz.it', 'allianz.it', 'Compagnia'),
  ('AXA Italia', 'https://www.axa.it', 'axa.it', 'Compagnia'),
  ('Zurich Italia', 'https://www.zurich.it', 'zurich.it', 'Compagnia'),
  ('Reale Mutua', 'https://www.realemutua.it', 'realemutua.it', 'Compagnia'),
  ('Groupama', 'https://www.groupama.it', 'groupama.it', 'Compagnia'),
  ('Vittoria Assicurazioni', 'https://www.vittoriaassicurazioni.com', 'vittoriaassicurazioni.com', 'Compagnia'),
  ('Sara Assicurazioni', 'https://www.sara.it', 'sara.it', 'Compagnia'),
  ('ITAS Mutua', 'https://www.gruppoitas.it', 'gruppoitas.it', 'Compagnia'),
  ('Helvetia Italia', 'https://www.helvetia.it', 'helvetia.it', 'Compagnia'),
  ('HDI Assicurazioni', 'https://www.hdiassicurazioni.it', 'hdiassicurazioni.it', 'Compagnia'),
  ('Intesa Sanpaolo Assicura', 'https://www.intesasanpaoloassicura.com', 'intesasanpaoloassicura.com', 'Compagnia'),
  ('Poste Vita', 'https://www.postevita.it', 'postevita.it', 'Compagnia'),
  ('Alleanza', 'https://www.alleanza.it', 'alleanza.it', 'Compagnia'),
  ('Genertel', 'https://www.genertel.it', 'genertel.it', 'Compagnia'),
  ('Linear', 'https://www.linear.it', 'linear.it', 'Compagnia'),
  ('Verti', 'https://www.verti.it', 'verti.it', 'Compagnia'),
  ('Prima Assicurazioni', 'https://www.prima.it', 'prima.it', 'Compagnia'),
  ('ConTe', 'https://www.conte.it', 'conte.it', 'Compagnia'),
  ('TUA Assicurazioni', 'https://www.tuaassicurazioni.it', 'tuaassicurazioni.it', 'Compagnia'),
  ('Nobis', 'https://www.nobis.it', 'nobis.it', 'Compagnia'),
  ('Assimoco', 'https://www.assimoco.it', 'assimoco.it', 'Compagnia'),
  ('Amissima', 'https://www.amissima.it', 'amissima.it', 'Compagnia'),
  ('ARAG', 'https://www.arag.it', 'arag.it', 'Compagnia — tutela legale'),
  ('DAS', 'https://www.das.it', 'das.it', 'Compagnia — tutela legale'),
  ('Europ Assistance', 'https://www.europassistance.it', 'europassistance.it', 'Compagnia — assistenza'),
  ('AIG', 'https://www.aig.com', 'aig.com', 'Compagnia'),
  ('Chubb', 'https://www.chubb.com', 'chubb.com', 'Compagnia'),
  ('Hiscox', 'https://www.hiscox.it', 'hiscox.it', 'Compagnia'),
  ('Allianz Trade', 'https://www.allianz-trade.com', 'allianz-trade.com', 'Compagnia — credito'),
  ('Coface', 'https://www.coface.it', 'coface.it', 'Compagnia — credito'),
  ('Lloyd''s', 'https://www.lloyds.com', 'lloyds.com', 'Compagnia / mercato')
ON CONFLICT (dominio) DO NOTHING;
