/** Intestazioni export (senza colonne codice Cd*, rg, St). */
export const TITOLI_DA_INCASSARE_COLUMNS = [
  { key: "cliente", header: "Cliente" },
  { key: "sede", header: "Sede" },
  { key: "specialist", header: "Specialist" },
  { key: "compagnia", header: "Compagnia" },
  { key: "ramo", header: "Ramo" },
  { key: "gruppoCompagnia", header: "Gruppo Compagnia" },
  { key: "polizza", header: "N. Polizza" },
  { key: "appendice", header: "Appendice" },
  { key: "descrizione", header: "Descrizione" },
  { key: "rifCig", header: "Rif./CIG" },
  { key: "competenza", header: "Competenza" },
  { key: "inizioPolizza", header: "Inizio Polizza" },
  { key: "scadenzaPolizza", header: "Scadenza Polizza" },
  { key: "inizioGaranzia", header: "Inizio Garanzia" },
  { key: "scadenzaGaranzia", header: "Scadenza Garanzia" },
  { key: "limiteMora", header: "Limite Mora" },
  { key: "valuta", header: "Valuta" },
  { key: "cambio", header: "Cambio" },
  { key: "premio", header: "Premio (€)" },
  { key: "provvAttive", header: "Provv. Attive (€)" },
  { key: "provvPassive", header: "Provv. Passive (€)" },
  { key: "produttore", header: "Produttore" },
  { key: "dataGarantito", header: "Data Garantito" },
  { key: "dataIncasso", header: "Data Incasso" },
  { key: "garantito", header: "Garantito" },
  { key: "giorniDisdetta", header: "Giorni Disdetta" },
  { key: "gruppoFinanziario", header: "Gruppo Finanziario" },
  { key: "filiale", header: "Filiale" },
  { key: "indotto", header: "Indotto" },
  { key: "tipoPortafoglio", header: "Tipo Portafoglio" },
  { key: "tipoTitolo", header: "Tipo Titolo" },
  { key: "rate", header: "Rate" },
  { key: "rinnovo", header: "Rinnovo" },
] as const;

export type TitoloDaIncassareRow = Record<(typeof TITOLI_DA_INCASSARE_COLUMNS)[number]["key"], string | number | null>;
